channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - pyg
  - aihabitat
dependencies:
  - ninja
  - gcc=11.2.0
  - gxx=11.2.0
  - sysroot_linux-64==2.17
  - binutils>=2.36
  - cudatoolkit-dev=11.7
  - python=3.9
  - cmake
  - pybind11
  - setuptools
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch3d
  - torchvision
  - torchaudio
  - mkl=2024.0
  - pip
  - habitat-sim=0.3.3
  - withbullet
  - pip: 
    - numpy==1.26.4 # certain deprecated operations were used in other deps
    - setuptools==69.5.1
    - omegaconf
    - tqdm
    - wandb
    - trimesh
    - datasets
    - torch==1.13.1
    - pytorch-lightning[extra]
    - tensorboard
    - cloudpickle
    - pycocotools
    - ipykernel
    - hydra-core
    - scipy
    - opencv-python
    - pybullet
    - pytest
    - open3d
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    - pandas
    - mss
    - matplotlib
    - torchmetrics
    - albumentations
    - connected-components-3d
    - pyntcloud
    - transformers==4.36.2
    - addict
    - yapf
    - timm
    - supervision