# @package _group_
batch_size: 8
n_iterations: 1
loss_margin: 0.3
thr: 0
exp_base_name: pipeline_gt
exp_name_training: ground_truth_sgd
lr: 0.0001
optimizer: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True

teacher_momentum: 0.99
temperature: 2

pipeline: Pipeline
student_model: TwoStageModel
pseudo_labeler_method: vanilla
alpha: 0.7
loss_weights:
  loss_centernet_*: 0.0
  loss_cls_*: 1.0
  loss_box_reg_*: 1.0

weight_sampler: False
update_target: True
reinit_online: False
use_gt: True