# @package _global_
defaults:
  - /benchmark/nav/objectnav/objectnav_hssd-hab.yaml
  - /habitat/task/measurements: 
    - top_down_map
  - override /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbds_agent
  - _self_

habitat:
  dataset:
    type: ObjectNav-v1
    split: val
    data_path: data/datasets/objectnav/hssd-hab/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets/hssd-hab/scenes
    content_scenes: ["*"]

  simulator:
    scene_dataset: "data/scene_datasets/hssd-hab/hssd-hab.scene_dataset_config.json"
    navmesh_include_static_objects: True
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.41, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 1.41, 0]
          semantic_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.41, 0]
        height: 1.41
        radius: 0.18
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
      enable_physics: True

DATA_GEN:
  seed: 0
  min_pixel_area: 500
  frame_height: 480
  frame_width: 640
  meters_per_grid_pixel: 0.1
  viewpoint_spacing: 0.5
  turn_angle: 30
  per_class_num_samples: 20
  vocab: NYU40
  dataset:
    data_root: datasets/
    dataset_name: hssd_od_nyu40
    splits:
      - split_name: hssd_od_nyu40_small
        scenes_to_include: [
          "102343992",
          "102344022",
          "102344049",
        ]
      - split_name: hssd_od_nyu40_full
        scenes_to_include: [
          "102343992",
          "102344022",
          "102344049",
          "102344094",
          "102344115",
          "102344193",
          "102344250",
          "102344280",
          "102344307",
          "102344328",
          "102344403",
          "102344439",
          "102344457",
          "102344469",
          "102344529",
          "102815835",
          "102815859",
          "102816009",
          "102816036",
          "102816051",
          "102816066",
          "102816114",
          "102816216",
          "102816600",
          "102816615",
          "102816627",
          "102816729",
          "102816756",
          "102816786",
          "102816852",
          "102817053",
          "102817140",
          "102817200"
        ]