# @package _global_
defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/task/measurements: 
    - top_down_map
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbds_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    scene_dataset: "data/scene_datasets/hssd-hab/hssd-hab.scene_dataset_config.json"
    navmesh_include_static_objects: True
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.41, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 1.41, 0]
          semantic_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.41, 0]
        height: 1.41
        radius: 0.18
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
      enable_physics: True
  dataset:
    type: PointNav-v1
    split: val
    data_path: data/datasets/habitat_active_od/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets/hssd-hab/scenes
    content_scenes: ["*"]

ONLINE_TRAINING:
  collection_dir: datadump/collection/
  num_episodes: 100
  steps_per_episode: 50
  batch_size: 1
  scenes: [
    "103997403_171030405",
    "103997424_171030444",
    "103997445_171030492",
    "103997460_171030507",
    "103997478_171030525",
    "103997478_171030528",
    "103997541_171030615",
    "103997562_171030642",
    "103997586_171030666",
    "103997586_171030669",
  ]