# run_name changed from ds_filter_empty -- that's the old 20/4 collection, doesn't have the 5 new scenes
run_name: hssd
trainer_name: randomteleportbaseline
steps_per_episode: 500
filter_empty: True

object_params:
  env_name: "HSSD-HAB"
  vocab_name: "HSSD80"
  area_thr: 500
  filter_low_visibility: True
  min_visibility_fraction: 0.15
  filter_out_classes: [ "alarm_clock", "animal", "bench", "bicycle", "blender", "book",
    "bottle", "bowl", "breadbin", "camera", "candle", "car", "carpet",
    "ceiling_lamp", "clothing", "coffee_maker", "colander",
    "couch", "cushion", "dishwasher", "door", "drinkware", "earphone",
    "exercise_bike", "eyeglasses", "filing_cabinet", "floor_lamp", "flower", "fridge",
    "grandfather_clock", "kettle", "kitchen_scale", "laptop", "mantel_clock", "microwave",
    "mixing_bowl", "mobile_phone", "motorcycle", "oven", "pan", "pathway_light", "person", "phone",
    "picture_frame", "plate", "plush_toy", "pot", "printer", "range_hood",
    "shoes", "sink", "soap_dispenser", "spicemill", "stand",
    "table_lamp", "teapot", "toaster", "toiletry", "trashcan", "tray", "treadmill",
    "tree", "vase", "wall_clock", "wall_lamp", "wardrobe", "washer_dryer", "window"]

train_scenes: [
  "102344022", "102817053", "104348133_171513054", "105515175_173104107", "106366371_174226743",
  "102344049", "102817200", "104348160_171513093", "105515211_173104179", "106366434_174226881",
  "102344115", "103997403_171030405", "104348181_171513120", "105515235_173104215", "106878945_174887058",
  "102344193", "103997424_171030444", "104348202_171513150", "105515286_173104287", "106879023_174887148",
  "102344094", "102344250", "102344280", "102344307", "102344328",
]
val_scenes: [
  "102343992", "102816756", "104348328_171513363", "105515379_173104395", "102344403",
]
