run_name: procthor
steps_per_episode: 500
filter_empty: False

object_params:
  env_name: "ProcTHOR-hab"
  vocab_name: "ProcTHOR-native"
  area_thr: 1000
  filter_low_visibility: True
  min_visibility_fraction: 0.15
  filter_classes: [ "Toaster", "Microwave", "Fridge", "Cabinet", "Chair", "DiningTable",
    "CounterTop", "Television", "Toilet", "Bathtub", "Bed", "Mirror", "ArmChair", "Ottoman",
    "Sofa", "Shelf", "Dresser", "Desk", "SideTable", "TVStand", "CoffeeTable", "ShelvingUnit",
    "Stool", "WashingMachine" ]

train_scenes: [
  "ProcTHOR-Train-0", "ProcTHOR-Train-1", "ProcTHOR-Train-2", "ProcTHOR-Train-3",
  "ProcTHOR-Train-4", "ProcTHOR-Train-5", "ProcTHOR-Train-6", "ProcTHOR-Train-7",
  "ProcTHOR-Train-8", "ProcTHOR-Train-9", "ProcTHOR-Train-10", "ProcTHOR-Train-11",
  "ProcTHOR-Train-12", "ProcTHOR-Train-13", "ProcTHOR-Train-14", "ProcTHOR-Train-15",
  "ProcTHOR-Train-16", "ProcTHOR-Train-17", "ProcTHOR-Train-18", "ProcTHOR-Train-19",
  "ProcTHOR-Train-20", "ProcTHOR-Train-21", "ProcTHOR-Train-22", "ProcTHOR-Train-23",
  "ProcTHOR-Train-24",
]
val_scenes: [
  "ProcTHOR-Val-0", "ProcTHOR-Val-1", "ProcTHOR-Val-2", "ProcTHOR-Val-3", "ProcTHOR-Val-4",
]
